### ISSUE TITLE
TypeError: cb is not a function

### ISSUE THREAD

**Issue by mrider75** [mruettgers/vallox-mqtt-bridge#2]
Hallo Michael,

erstmal vielen Dank für das tolle Docker-Image!
Es funktioniert alles super bis auf eine Sache:

ventilation/unit/1/metrics/get ["A_CYC_HOME_SPEED_SETTING", "A_CYC_AWAY_SPEED_SETTING"]

Wenn ich das aufrufe, wirft es mir folgenden Fehler zurück und der Docker-Container wird beendet:

> Loading config from file /config/vallox-mqtt-bridge.yml
> 
> Config: {
>   fetch_interval: 10,
>   vallox: { unit: { host: '192.168.10.36', port: 80 } },
>   mqtt: {
>     broker: { host: '192.168.10.48' },
>     base_topic: 'ventilation/unit/1'
>   },
>   metrics: [
>     'A_CYC_FAN_SPEED',
>     'A_CYC_TEMP_EXTRACT_AIR',
>     'A_CYC_TEMP_EXHAUST_AIR',
>     'A_CYC_TEMP_OUTDOOR_AIR',
>     'A_CYC_TEMP_SUPPLY_CELL_AIR',
>     'A_CYC_TEMP_SUPPLY_AIR',
>     'A_CYC_RH_LEVEL',
>     'A_CYC_CO2_LEVEL',
>     'A_CYC_EXTR_FAN_SPEED',
>     'A_CYC_SUPP_FAN_SPEED',
>     'A_CYC_RH_VALUE'
>   ]
> }
> 
> TypeError: cb is not a function
>     at /opt/vallox-mqtt-bridge/index.js:77:17
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> /opt/vallox-mqtt-bridge/index.js:81
>                 cb(err)
>                 ^
> TypeError: cb is not a function
>     at /opt/vallox-mqtt-bridge/index.js:81:17
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> Node.js v18.12.1

Danke und viele Grüße, 
Martin

**Comment by mruettgers** [comment]
Hallo Martin,

danke für den Bug-Report.
Ich habe gerade eine neue Version hochgeladen, die das Problem beheben sollte.

Viele Grüße,
Michael

**Comment by mrider75** [comment]
Hi Michael,

super, jetzt funktioniert es!
Vielen lieben Dank!!!

Gruß,
Martin
